### ISSUE TITLE
【API】環境変数から設定を変更できるようにする

### ISSUE THREAD

**Issue by HEKUCHAN** [WebAppClub/tech-library#21]
- データベースの設定をできるようにする
- APIサーバーの設定ができるようにする

`.env`があれば、そのファイルから取得し、
なければ環境変数から取得するようなイメージ

※ #18 **が完了した後に**

**Comment by HEKUCHAN** [comment]
- データベースの設定をできるようにする
- APIサーバーの設定ができるようにする

`.env`があれば、そのファイルから取得し、
なければ環境変数から取得するようなイメージ

**Comment by ryuma017** [comment]
ホストマシン上では問題なく実行できるけど、
Docker上だとpostgresに接続できなくてエラーになる。

techlib_api のログ
```
thread 'main' panicked at 'Failed to configure a pool.: Error(Some("could not connect to server: Connection refused\n\tIs the server running on host \"127.0.0.1\" and accepting\n\tTCP/IP connections on port 5432?\n"))', src/startup.rs:49:10

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[Finished running. Exit status: 101]
```

**Comment by HEKUCHAN** [comment]
🤔 
![image](https://user-images.githubusercontent.com/70084358/176583073-6051915f-f38a-4d40-8ded-8e1bbc1fdf3a.png)

**Comment by HEKUCHAN** [comment]
なおった
![Uploading image.png…]()

**Comment by HEKUCHAN** [comment]
なおった
![image](https://user-images.githubusercontent.com/70084358/176584720-5fc1d0bb-66fb-48db-b1c3-b4cf997734d2.png)

**Comment by HEKUCHAN** [comment]
@ryuma017

**Comment by ryuma017** [comment]
@HEKUCHAN 
ないす〜ありがとう
docker わからんﾅｷﾅｷ
